# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

shared: &default
  fb_app_id:                <%= ENV['FB_APP_ID'] %>
  fb_app_secret:            <%= ENV['FB_APP_SECRET'] %>
  fb_oauth_token:           <%= ENV['FB_OAUTH_TOKEN'] %>
  google_cse_id:            <%= ENV['G_CSE_ID'] %>
  google_api_key:           <%= ENV['G_API_KEY'] %>
  mashape_api_key:          <%= ENV['MASHAPE_API_KEY'] %>
  rotten_tomatoes_api_key:  <%= ENV['RT_API_KEY'] %>
  tmdb_api_key:             <%= ENV['TMDB_API_KEY'] %>

development:
  <<: *default
  secret_key_base: f94692736b53171182f37a05e979b833976665d9b8b2ec9332e17b7768ad598a332a5b1d21fd469669505d1aff1c12a273d84f9f4c3278a8ff9cdbec87212ed5
  hello: world

test:
  <<: *default
  secret_key_base: abcf9689824d1d332746cc7d09a849900a33494eab47a8b39de37635c11c6dd07c3f69616291faa2616451dcf9c487462aeb6e9a4260d0d5c39fb3d088c0c74a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
